name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install Django djangorestframework
          fi

      - name: Self-check A1–A5 (skip if command absent)
        run: |
          if [ -f backend/manage.py ] && grep -q "verify_a1a5" -r backend/core/management/commands 2>/dev/null; then
            python backend/manage.py verify_a1a5
          else
            echo "verify_a1a5 not found — skipping"
          fi

      - name: Unit tests
        run: |
          if [ -f backend/manage.py ]; then
            python backend/manage.py test -v 2
          else
            echo "backend/manage.py not found"; exit 1
          fi
